### ISSUE TITLE
homebridge-govee requires Node.js version of ^14.20.1 || ^16.18.0 || ^18.11.0, doesn't match node version in the docker container: v16.15.0.

### ISSUE THREAD

**Issue by wez** [bwp91/homebridge-govee#345]
### What issue do you have? Please be as thorough and explicit as possible.

When I start homebridge I see the warning message:

```
The plugin "homebridge-govee" requires Node.js version of ^14.20.1 || ^16.18.0 || ^18.11.0 which does not satisfy the current Node.js version of v16.15.0.
```

It doesn't appear to hurt anything, but I'd like to make the warning go away. The version of nodejs is controlled by the homebridge docker image and I "can't" change it.

Can homebridge-govee adjust the version requirements to avoid that warning, or otherwise resolve whatever incompatibility that lead to the higher version requirement?

### Details of your setup.

Here's my docker-compose.yml:

```yaml
version: '3.0'
services:
  homebridge:
    image: oznu/homebridge:ubuntu
    container_name: homebridge
    restart: always
    network_mode: host
    privileged: true
    environment:
      - TZ=America/Phoenix
      - PGID=1000
      - PUID=1000
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=8080
    volumes:
      - ./homebridge:/homebridge
      - /run/dbus:/run/dbus:ro
```

* Which version of Homebridge/HOOBS do you have?

1.5.1

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.

This is running in docker on a linux box running ubuntu.

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?

I think I've seen this with every version I've tried. I'm running version 7.1.1 at the moment.

* Which Govee devices do you have that are causing issues? Please include product models if applicable.

N/A
